### ISSUE TITLE
issue with "api_key" in test.camera.js file

### ISSUE THREAD

**Issue by fmanclossi** [ibmtjbot/tjbot#109]
Hi, I've setup a new TJBot just now following manual installation.
Everything works fine except camera test. This is the output.

```
pi@TJBOTtest:~/Desktop/tjbot/bootstrap/tests $ sudo node test.camera.js 
verbose: TJBot initializing Camera
verbose: TJBot initializing visual_recognition service
assert.js:49
  throw new AssertionError(obj);
  ^

AssertionError [ERR_ASSERTION]: credentials for the visual_recognition service missing 'apikey'
    at TJBot._createServiceAPI (/home/pi/node_modules/tjbot/lib/tjbot.js:524:9)
    at new TJBot (/home/pi/node_modules/tjbot/lib/tjbot.js:116:18)
    at Object.<anonymous> (/home/pi/Desktop/tjbot/bootstrap/tests/test.camera.js:31:10)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:695:10)
    at startup (internal/bootstrap/node.js:201:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:516:3)

```
I was able to fix it changing "api_key" to "apikey" in test.camera.js file, but i?m asking if it's ok to change it.

Thanks in advance
Ferruccio

**Comment by jweisz** [comment]
This is a great question. The previous authentication method for Visual Recognition used an `api_key`, which is different than the current method which uses the IAM `apikey`.

For the `test.camera.js`, it's not actually interacting with Visual Recognition, so the actual api key used by the script doesn't matter. Therefore, it's perfectly fine to change `api_key` to `apikey` with no ill effect.

But, if/when you're writing code that does use Visual Recognition, you may need to re-create the service in order to get an instance that uses the new IAM authentication (I'm not sure if you can 'upgrade' an existing service instance). E.g.
- delete your existing instance of the Visual Recognition service
- create a new instance of the Visual Recognition service
- copy the new IAM `apikey` into your config.js file

Closing this issue, but please reopen it if you have any further questions. Thanks!
