### ISSUE TITLE
Error executing conversation.js in the first time

### ISSUE THREAD

**Issue by ing-jlgonzalezb** [ibmtjbot/tjbot#111]
Hi eveyone. I need help, I installed TJBOT into my Raspberry PI 3 (and node js 9), when execute `sudo node conversation.js` (trying conversation recipe), receive the following message:

```
verbose: TJBot initializing microphone
verbose: TJBot initializing LED
verbose: TJBot initializing servo motor on PIN 7
verbose: TJBot initializing assistant service
verbose: TJBot initializing speech_to_text service
verbose: TJBot initializing text_to_speech service
verbose: TJBot initializing visual_recognition service
/home/pi/tjbot/recipes/conversation/node_modules/tjbot/lib/tjbot.js:542
throw new Error(
^
Error: Missing authentication credentials for tone_analyzer service: username/password or apikey are required.
at TJBot._createServiceAPI (/home/pi/tjbot/recipes/conversation/node_modules/tjbot/lib/tjbot.js:542:19)
at new TJBot (/home/pi/tjbot/recipes/conversation/node_modules/tjbot/lib/tjbot.js:116:18)
at Object.<anonymous> (/home/pi/tjbot/recipes/conversation/conversation.js:40:10)
at Module._compile (internal/modules/cjs/loader.js:654:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
at Module.load (internal/modules/cjs/loader.js:566:32)
at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
at Function.Module._load (internal/modules/cjs/loader.js:498:3)
at Function.Module.runMain (internal/modules/cjs/loader.js:695:10)
at startup (internal/bootstrap/node.js:201:19)
at bootstrapNodeJSCore (internal/bootstrap/node.js:516:3)
```

Note: I reinstalled Raspbian, upgraded and updated, then execute all the steps, same error.

**Comment by jweisz** [comment]
Please see this comment: https://github.com/ibmtjbot/tjbot/issues/104#issuecomment-450026228
