### ISSUE TITLE
conversation.js : error: Cannot find module 'rpi-ws281x-native'

### ISSUE THREAD

**Issue by Dswag** [ibmtjbot/tjbot#116]
I don't know what that is or how I can fix it. All I can guess is that it's something inside the                                   node modules folder.

sudo node conversation.js
verbose: TJBot initializing microphone
verbose: TJBot initializing LED
internal/modules/cjs/loader.js:582
    throw err;
    ^

Error: Cannot find module 'rpi-ws281x-native'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at TJBot._setupLED (/home/pi/Desktop/cleantjbot/recipes/conversation/node_modules/tjbot/lib/tjbot.js:230:18)
    at TJBot.<anonymous> (/home/pi/Desktop/cleantjbot/recipes/conversation/node_modules/tjbot/lib/tjbot.js:63:18)
    at Array.forEach (<anonymous>)
    at new TJBot (/home/pi/Desktop/cleantjbot/recipes/conversation/node_modules/tjbot/lib/tjbot.js:56:14)
    at Object.<anonymous> (/home/pi/Desktop/cleantjbot/recipes/conversation/conversation.js:40:10)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
    at startup (internal/bootstrap/node.js:285:19)

______________________________________________________________________

is in an issue with a missing dependency?

Thanks!!

**Comment by jweisz** [comment]
Hi @Dswag. Apologies for the late reply, I was on leave from work at the end of last year when you opened this issue. This is a dependency issue. You will need to do an `npm install` to install that library (and all the other libraries needed by that recipe). Then you can run the recipe.
