### ISSUE TITLE
sentiment_analysis throwing error at 105:48

### ISSUE THREAD

**Issue by ciptsrc** [ibmtjbot/tjbot#119]
When executing node sentiment.js I get the following error at line 105:

Unhandled rejection TypeError: Cannot read property 'forEach' of undefined
    at /home/pi/tjbot/recipes/sentiment_analysis/sentiment.js:105:48
    at tryCatcher (/home/pi/tjbot/recipes/sentiment_analysis/node_modules/bluebi                                                                                                                                                             rd/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/pi/tjbot/recipes/sentiment_analy                                                                                                                                                             sis/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/pi/tjbot/recipes/sentiment_analysis/node_mo                                                                                                                                                             dules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/pi/tjbot/recipes/sentiment_analysis/node_m                                                                                                                                                             odules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/pi/tjbot/recipes/sentiment_analysis/node_m                                                                                                                                                             odules/bluebird/js/release/promise.js:694:18)
    at _drainQueueStep (/home/pi/tjbot/recipes/sentiment_analysis/node_modules/b                                                                                                                                                             luebird/js/release/async.js:138:12)
    at _drainQueue (/home/pi/tjbot/recipes/sentiment_analysis/node_modules/blueb                                                                                                                                                             ird/js/release/async.js:131:9)
    at Async._drainQueues (/home/pi/tjbot/recipes/sentiment_analysis/node_module                                                                                                                                                             s/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/pi/tjbot/recipes/sen                                                                                                                                                             timent_analysis/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:763:18)
    at tryOnImmediate (timers.js:734:5)
    at processImmediate (timers.js:716:5)

When looking at the code I see it stops when category.category_id = = "emotion_tone" is called:

`tj.analyzeTone(text).then(function(tone) {
            tone.document_tone.tone_categories.forEach(function(category) {
                if (category.category_id == "emotion_tone") {
                    // find the emotion with the highest confidence
                    var max = category.tones.reduce(function(a, b) {
                        return (a.score > b.score) ? a : b;
                    });
`

Something is wrong with the code, can it be that "emotion_tone" is not instanciated?
Can anyone tell me how to run the code in debug mode?

Thanks for any help

**Comment by jweisz** [comment]
Potentially fixed in #125. Will test, then merge and accept later this week.
