### ISSUE TITLE
Speech to Text Module Failing to Run

### ISSUE THREAD

**Issue by stonebraker** [ibmtjbot/tjbot#147]
Hi, I'm attempting to run the SpeechToText module and it is failing. I will paste the output from my attempt to execute stt.js. The installation of the Speech to Text package produced some errors as well. It's very long. I'll paste it in a subsequent reply. Needless to say, pigpio and rpi-ws281x-native both failed to install properly.

I'm using a fresh pi from the adafruit tjbot kit. The sd card has been formatted, had noobs installed, then Raspbian (Buster), then the TJBot bootstrap (node v10.15.2, npm v5.8.0). I kept default names and locations. So this is super clean as far as I can tell. Please let me know if I missed a step.

Thanks in advance for your help!
Jason
=========================================
Output from execution of stt.js:

pi@raspberrypi:~/Desktop/tjbot/recipes/speech_to_text $ node stt.js
internal/modules/cjs/loader.js:628
    throw err;
    ^

Error: Cannot find module 'tjbot'
Require stack:
- /home/pi/Desktop/tjbot/recipes/speech_to_text/stt.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:625:15)
    at Function.Module._load (internal/modules/cjs/loader.js:527:27)
    at Module.require (internal/modules/cjs/loader.js:683:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/home/pi/Desktop/tjbot/recipes/speech_to_text/stt.js:17:13)
    at Module._compile (internal/modules/cjs/loader.js:777:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:788:10)
    at Module.load (internal/modules/cjs/loader.js:643:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:840:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/home/pi/Desktop/tjbot/recipes/speech_to_text/stt.js' ]
}

**Comment by stonebraker** [comment]
Output from npm install of the Speech to Text package:

pi@raspberrypi:~/Desktop/tjbot/recipes/speech_to_text $ sudo npm install

npm WARN npm npm does not support Node.js v10.15.2
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 4, 6, 7, 8, 9.
npm WARN npm You can find the latest version at https://nodejs.org/
npm WARN deprecated watson-developer-cloud@3.18.4: DeprecationWarning: watson-developer-cloud moved to ibm-watson. To get updates, use the new package.
npm WARN deprecated @types/form-data@2.5.0: This is a stub types definition. form-data provides its own type definitions, so you do not need this installed.

> pigpio@0.4.0 install /home/pi/Desktop/tjbot/recipes/speech_to_text/node_modules/pigpio
> node-gyp rebuild

gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/home/pi/Desktop/tjbot/recipes/speech_to_text/node_modules/pigpio/build'
gyp ERR! System Linux 4.19.58-v7+
gyp ERR! command "/usr/bin/node" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/pi/Desktop/tjbot/recipes/speech_to_text/node_modules/pigpio
gyp ERR! node -v v10.15.2
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 

> rpi-ws281x-native@0.8.2 install /home/pi/Desktop/tjbot/recipes/speech_to_text/node_modules/rpi-ws281x-native
> node-gyp rebuild

gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/home/pi/Desktop/tjbot/recipes/speech_to_text/node_modules/rpi-ws281x-native/build'
gyp ERR! System Linux 4.19.58-v7+
gyp ERR! command "/usr/bin/node" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/pi/Desktop/tjbot/recipes/speech_to_text/node_modules/rpi-ws281x-native
gyp ERR! node -v v10.15.2
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 

> sleep@5.2.4 install /home/pi/Desktop/tjbot/recipes/speech_to_text/node_modules/sleep
> node-gyp rebuild

gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/home/pi/Desktop/tjbot/recipes/speech_to_text/node_modules/sleep/build'
gyp ERR! System Linux 4.19.58-v7+
gyp ERR! command "/usr/bin/node" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/pi/Desktop/tjbot/recipes/speech_to_text/node_modules/sleep
gyp ERR! node -v v10.15.2
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: pigpio@0.4.0 (node_modules/pigpio):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: pigpio@0.4.0 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: rpi-ws281x-native@0.8.2 (node_modules/rpi-ws281x-native):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: rpi-ws281x-native@0.8.2 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sleep@5.2.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sleep@5.2.4 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-07-24T18_59_55_967Z-debug.log

**Comment by stonebraker** [comment]
This hasn't been resolved. I'm closing it so I can ask a more specific helpful question.
