### ISSUE TITLE
conversation.js issue with Raspbian Stretch

### ISSUE THREAD

**Issue by mshaz** [ibmtjbot/tjbot#150]
Hi I need help. The tests works fine but am having the issues below. I already added all the required credentials. 

Thank you

pi@raspberrypi:~/Desktop/tjbot/recipes/conversation $ sudo node conversation.js
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module './build/Release/node_sleep.node'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/pi/Desktop/tjbot/recipes/conversation/node_modules/sleep/index.js:1:13)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/pi/Desktop/tjbot/recipes/conversation/node_modules/tjbot/lib/tjbot.js:24:15)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)

**Comment by jweisz** [comment]
It looks like the `sleep` module didn't get installed. Try `npm install` again? Or maybe first wipe out the `node_modules` folder and then `npm install`?

Let me know how it goes.

**Comment by mshaz** [comment]
Hi ,

I still have errors.

**Comment by jweisz** [comment]
Closing due to inactivity, but please re-open with more description about the problem if you still have issues.
