### ISSUE TITLE
TJ Bot Error

### ISSUE THREAD

**Issue by JoshNahourai** [ibmtjbot/tjbot#70]
I followed this url steps : http://learn.linksprite.com/raspberry-pi/build-a-talking-robot-with-watson/

& after step 7 I got these errors : 

pi@raspberrypi:~/tjbot/recipes/conversation $ :  node conversation.js
 
module.js:471
    throw err;
    ^

Error: Cannot find module './config'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/pi/tjbot/recipes/conversation/conversation.js:18:14)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:383:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:496:3

& I couldn’t fix it yet.

**Comment by victordibia** [comment]
Hi @JoshNahourai 

- The link you have followed appears to have incorrect instructions.
Please use the instructions [we provide on instructables] (http://www.instructables.com/id/Build-a-Talking-Robot-With-Watson-and-Raspberry-Pi/).

- The error above suggests you do not have the `config.js` file in your conversation folder.
Please ensure you do have it and retry. 

Note .. the repository contains a `config.default.js` file which you have to rename to `config.js`  

-V.
