### ISSUE TITLE
solvemy problem

### ISSUE THREAD

**Issue by arifasultana** [ibmtjbot/tjbot#74]
verbose: TJBot initializing microphone
verbose: TJBot initializing conversation service
/home/pi/tjbot/recipes/conversation/node_modules/watson-developer-cloud/lib/base_service.js:73
      throw new Error('Argument error: username and password are required unless use_unauthenticated is set');
      ^

Error: Argument error: username and password are required unless use_unauthenticated is set
    at ConversationV1.BaseService.initCredentials (/home/pi/tjbot/recipes/conversation/node_modules/watson-developer-cloud/lib/base_service.js:73:13)
    at ConversationV1.BaseService (/home/pi/tjbot/recipes/conversation/node_modules/watson-developer-cloud/lib/base_service.js:44:18)
    at new ConversationV1 (/home/pi/tjbot/recipes/conversation/node_modules/watson-developer-cloud/conversation/v1.js:31:15)
    at TJBot._createServiceAPI (/home/pi/tjbot/recipes/conversation/node_modules/tjbot/lib/tjbot.js:341:34)
    at new TJBot (/home/pi/tjbot/recipes/conversation/node_modules/tjbot/lib/tjbot.js:88:18)
    at Object.<anonymous> (/home/pi/tjbot/recipes/conversation/conversation.js:37:10)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:427:7)
    at startup (bootstrap_node.js:151:9)
    at bootstrap_node.js:542:3

plzz help

**Comment by victordibia** [comment]
The error above suggests you have not set the username and password for your conversation service. Please verify you have added these in your `config.js` file.


-V.
