### ISSUE TITLE
Syntax errors

### ISSUE THREAD

**Issue by ailstyn** [ibmtjbot/tjbot#85]
Hi all, trying to get my new TJBot setup in my classroom and I've run into a snag. 

pi@TJBot:~/tjbot/recipes/conversation $ sudo node conversation.js
/home/pi/tjbot/recipes/conversation/config.js:25
	username: 'ecd329e7-83ab-4d32-95a5-418d5b174428''
	                                                ^
SyntaxError: Invalid or unexpected token
    at createScript (vm.js:53:10)
    at Object.runInThisContext (vm.js:95:10)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/pi/tjbot/recipes/conversation/conversation.js:18:14)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)

I tried rebuilding conversation.js from git, but no effect. I'm not super familiar with javascript so I do not know what the modules are in reference to.

**Comment by victordibia** [comment]
Hi

It looks like you have an additional quote at the end of your username.

'ecd329e7-83ab-4d32-95a5-418d5b174428''

Removing the quote should solve that issue.
-V
