### ISSUE TITLE
Error when running stt.js

### ISSUE THREAD

**Issue by Maggiieek** [ibmtjbot/tjbot#86]
Hi I've been trying to run the stt.js file and everytime I get this error 

/home/pi/tjbot/recipes/speech_to_text/node_modules/tjbot/lib/tjbot.js:924
TJBot.prototype.pulse = function(color, duration = 1.0) {
                                                 ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/pi/tjbot/recipes/speech_to_text/node_modules/tjbot/index.js:1:80)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)

Anyone have any ideas what the problem might be?

**Comment by victordibia** [comment]
Hi @Maggiieek ,
Just a quick question .. have you made any changes to the tjbot.js file? We recommend this file is not updated in anyway. Perhaps a fresh installation (delete the repo, clone, run npm install) ?

-V.

**Comment by jweisz** [comment]
This might be an error with an old version of Node. What version of Node are you running?  Try installing a newer one? e.g.

```
curl -sL https://deb.nodesource.com/setup_9.x | sudo -E bash -
sudo apt-get install -y nodejs
```

**Comment by jweisz** [comment]
Closing this issue due to inactivity. Please re-open if you have additional questions.
